name: capstone

services:
  backend:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/uploads
    depends_on:
      - db

  db:
    image: mongo:latest
    expose:
      - 27017
    env_file:
      - ./.env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro