name: capstone

services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo:latest
    expose:
      - 27017
    env_file:
      - ./.env